### ISSUE TITLE
Instructions for Postman Incorrect

### ISSUE THREAD

**Issue by jbates58** [CiscoDevNet/cloud-security#3]
Hello, upon following the instructions as written to get the "Access Token" it did not work.

Im not sure if there is a standard format or protocol for issues, but upon trying to connect to the Umbrella server to get the bearer token, I kept getting authorization issues. I found a solution and it is below. can you please update the instructions.

The solution to this is as follows

Under `Authorization` set it to `Basic Auth`
insert the `API key` as the `Username` and `API Secret` as the `Password`

Then head over to the `Body` Tab and select `RAW`, then insert the line below
>grant_type=Client_credentials

Thanks.

Jason

**Comment by kbhawkey** [comment]
Thanks for logging an issue and contributing. We will update the README.
